#pragma once
// This file aggregates the pre-compiled HLSL bytecodes generated by CMake via fxc.exe /Fh.

// The CMake custom command places the headers in the build/bin directory.
// We must make sure the build directory is in our include path, or just include them if CMake puts them there.
// Actually, CMake places them in SHADER_OUTPUT_DIR (which is ${CMAKE_BINARY_DIR}/bin).
// So we just include them here:

#include "stereo_warp_cs_dx11.h"
#include "stereo_resolve_cs_dx11.h"
#include "disocclusion_fill_cs_dx11.h"
#include "bilateral_blur_cs_dx11.h"
#include "bilateral_blend_cs_dx11.h"
#include "depth_reprojection_cs_dx11.h"
