[FilterPlugin]
; Marketplace packaging filter whitelist
/Config/...
/Source/...
/Resources/...
/Binaries/Win64/nexvr_sdk.dll
/Binaries/Win64/nexvr_sdk.lib
/Binaries/Win64/nexvr_unreal.dll
/Binaries/Win64/nexvr_unreal.lib
/README.md
/NexVR.uplugin
