# CMake generated Testfile for 
# Source directory: C:/Users/sathi/.gemini/antigravity/scratch/vr-inject
# Build directory: C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[LoggerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_logger.exe")
  set_tests_properties([=[LoggerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;611;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[LoggerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_logger.exe")
  set_tests_properties([=[LoggerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;611;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[LoggerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_logger.exe")
  set_tests_properties([=[LoggerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;611;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[LoggerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_logger.exe")
  set_tests_properties([=[LoggerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;611;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
else()
  add_test([=[LoggerTest]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ConfigManagerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_config_manager.exe")
  set_tests_properties([=[ConfigManagerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;612;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ConfigManagerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_config_manager.exe")
  set_tests_properties([=[ConfigManagerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;612;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ConfigManagerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_config_manager.exe")
  set_tests_properties([=[ConfigManagerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;612;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ConfigManagerTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_config_manager.exe")
  set_tests_properties([=[ConfigManagerTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;612;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
else()
  add_test([=[ConfigManagerTest]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MatrixClassifierTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_matrix_classifier.exe")
  set_tests_properties([=[MatrixClassifierTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;613;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MatrixClassifierTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_matrix_classifier.exe")
  set_tests_properties([=[MatrixClassifierTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;613;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MatrixClassifierTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_matrix_classifier.exe")
  set_tests_properties([=[MatrixClassifierTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;613;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MatrixClassifierTest]=] "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/build_baseline/bin/test_matrix_classifier.exe")
  set_tests_properties([=[MatrixClassifierTest]=] PROPERTIES  COMPILE_OPTIONS "/W4" _BACKTRACE_TRIPLES "C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;613;add_test;C:/Users/sathi/.gemini/antigravity/scratch/vr-inject/CMakeLists.txt;0;")
else()
  add_test([=[MatrixClassifierTest]=] NOT_AVAILABLE)
endif()
subdirs("_deps/openxr-build")
subdirs("_deps/googletest-build")
