import { chromium } from 'playwright';
const b = await chromium.launch({executablePath: process.env.LOCALAPPDATA + '/ms-playwright/chromium-1228/chrome-win64/chrome.exe'});
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
p.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
await p.goto('http://127.0.0.1:8905/index.html', { waitUntil: 'load' });
await p.waitForTimeout(2500);
await p.screenshot({ path: '_hero.png' });
await p.setViewportSize({ width: 390, height: 844 });
await p.waitForTimeout(600);
await p.screenshot({ path: '_hero-m.png' });
console.log('errors:', errs.length ? errs.join(' | ') : 'none');
await b.close();
